"use client";

import React, { useState } from "react";
import { ShieldAlert, Users, Radio, AlertOctagon, CheckCircle, Download, FileText, ChevronRight } from "lucide-react";

export default function CartelRadar() {
  const [downloaded, setDownloaded] = useState(false);

  const correlationMatrix = [
    { carrier: "IndiGo", indiGo: 1.00, airIndia: 0.94, spiceJet: 0.87, akasaAir: 0.82 },
    { carrier: "Air India", indiGo: 0.94, airIndia: 1.00, spiceJet: 0.89, akasaAir: 0.85 },
    { carrier: "SpiceJet", indiGo: 0.87, airIndia: 0.89, spiceJet: 1.00, akasaAir: 0.79 },
    { carrier: "Akasa Air", indiGo: 0.82, airIndia: 0.85, spiceJet: 0.79, akasaAir: 1.00 },
  ];

  const synchronizedEvents = [
    {
      route: "DEL-BOM",
      timestamp: "Today, 14:15 IST",
      leadTime: "T+1",
      carrier1: "IndiGo (+₹1,400 within 8 min)",
      carrier2: "Air India (+₹1,350 within 12 min)",
      correlation: "0.98",
      severity: "CRITICAL",
      reason: "Parallel last-minute inventory surge matching"
    },
    {
      route: "BOM-BLR",
      timestamp: "Yesterday, 18:30 IST",
      leadTime: "T+7",
      carrier1: "Air India Express (+₹900)",
      carrier2: "IndiGo (+₹850)",
      correlation: "0.95",
      severity: "HIGH",
      reason: "Weekend surcharge synchronicity without ATF change"
    },
    {
      route: "DEL-CCU",
      timestamp: "03 Sep, 11:00 IST",
      leadTime: "T+3",
      carrier1: "SpiceJet (+₹1,100)",
      carrier2: "IndiGo (+₹1,050)",
      correlation: "0.92",
      severity: "MEDIUM",
      reason: "Simultaneous dynamic pricing bucket lockout"
    }
  ];

  const handleExportDossier = () => {
    setDownloaded(true);
    const dossierText = `COMPETITION COMMISSION OF INDIA (CCI) & DGCA
ANTI-COMPETITIVE AIRFARE COLLUSION SURVEILLANCE DOSSIER
Generated by MoSPI APIx Engine (SIH26056)
Date: ${new Date().toISOString()}

1. EXECUTIVE RISK ASSESSMENT
- Algorithmic Price Synchronization Index: 88 / 100 (HIGH RISK)
- Primary Parallel Pricing Pair: IndiGo <-> Air India (Pearson r = 0.94)
- Statutory Reference: Section 3(3)(a) and 3(3)(b) of the Competition Act, 2002

2. INTER-CARRIER PRICE PARALLELISM MATRIX
IndiGo vs Air India: r = 0.94 (Significant parallel movement)
IndiGo vs SpiceJet: r = 0.87
Air India vs SpiceJet: r = 0.89

3. FLAG DETAILS
- Route DEL-BOM: Synchronized price surge observed within 12-minute window.
- Recommended Action: Issue show-cause directive requiring algorithmic pricing audit logs.
`;
    const blob = new Blob([dossierText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `CCI_Collusion_Dossier_${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    setTimeout(() => setDownloaded(false), 3000);
  };

  return (
    <div className="space-y-6">
      
      {/* Top Banner */}
      <div className="bg-gradient-to-r from-rose-900 to-slate-900 rounded-2xl p-6 text-white shadow-md border border-rose-800/40">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <ShieldAlert className="w-5 h-5 text-rose-400" />
              <h2 className="text-lg font-bold tracking-tight">Algorithmic Collusion & Parallel Pricing Radar</h2>
              <span className="bg-rose-500/20 text-rose-300 border border-rose-500/40 text-[10px] font-bold px-2 py-0.5 rounded">
                CCI Section 3(3)
              </span>
            </div>
            <p className="text-xs text-rose-200/80 max-w-2xl">
              Monitors inter-airline dynamic pricing algorithms to detect tacit collusion, coordinated capacity withholding, and synchronized fare spikes across major Indian carriers.
            </p>
          </div>

          <button
            onClick={handleExportDossier}
            className="bg-rose-600 hover:bg-rose-500 text-white font-semibold text-xs px-4 py-2.5 rounded-lg shadow-sm flex items-center gap-2 transition cursor-pointer self-start md:self-center"
          >
            {downloaded ? <CheckCircle className="w-4 h-4 text-emerald-300" /> : <Download className="w-4 h-4" />}
            {downloaded ? "Dossier Exported!" : "Export CCI Inquiry Dossier"}
          </button>
        </div>
      </div>

      {/* Metric Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        
        <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-xs">
          <div className="flex items-center justify-between text-slate-500 text-xs font-semibold mb-2">
            <span>Synchronization Score</span>
            <Radio className="w-4 h-4 text-rose-500 animate-pulse" />
          </div>
          <div className="text-3xl font-black text-rose-600 font-mono">88 / 100</div>
          <div className="mt-2 text-xs text-rose-700 font-medium bg-rose-50 px-2 py-1 rounded inline-block">
            Elevated Parallel Pricing Risk
          </div>
          <p className="text-[11px] text-slate-400 mt-2">
            Prices move in tandem within 15-min windows at a rate 3.4x higher than random walk.
          </p>
        </div>

        <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-xs">
          <div className="flex items-center justify-between text-slate-500 text-xs font-semibold mb-2">
            <span>Dominant Duopoly Share</span>
            <Users className="w-4 h-4 text-blue-500" />
          </div>
          <div className="text-3xl font-black text-slate-900 font-mono">89.4%</div>
          <div className="mt-2 text-xs text-slate-600 font-medium">
            IndiGo (63.2%) + Air India Group (26.2%)
          </div>
          <p className="text-[11px] text-slate-400 mt-2">
            Combined bilateral capacity creates high structural exposure to algorithmic follow-the-leader.
          </p>
        </div>

        <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-xs">
          <div className="flex items-center justify-between text-slate-500 text-xs font-semibold mb-2">
            <span>Synchronized Events (7D)</span>
            <AlertOctagon className="w-4 h-4 text-amber-500" />
          </div>
          <div className="text-3xl font-black text-amber-600 font-mono">14 Detected</div>
          <div className="mt-2 text-xs text-slate-600 font-medium">
            3 Critical • 7 High • 4 Medium
          </div>
          <p className="text-[11px] text-slate-400 mt-2">
            Automated notifications dispatched to DGCA Airfare Monitoring Cell.
          </p>
        </div>

      </div>

      {/* Correlation Heatmap Table */}
      <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-xs">
        <h3 className="text-sm font-bold text-slate-900 mb-1">Inter-Carrier Daily Pricing Correlation Matrix (Pearson r)</h3>
        <p className="text-xs text-slate-500 mb-4">Values close to 1.0 indicate strong price co-movement across identical route corridors.</p>

        <div className="overflow-x-auto">
          <table className="w-full text-xs text-left">
            <thead>
              <tr className="border-b border-slate-200 bg-slate-50 text-slate-600 uppercase text-[10px] tracking-wider">
                <th className="py-2.5 px-3">Carrier</th>
                <th className="py-2.5 px-3 text-center">IndiGo</th>
                <th className="py-2.5 px-3 text-center">Air India</th>
                <th className="py-2.5 px-3 text-center">SpiceJet</th>
                <th className="py-2.5 px-3 text-center">Akasa Air</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {correlationMatrix.map((row) => (
                <tr key={row.carrier} className="hover:bg-slate-50 font-mono">
                  <td className="py-3 px-3 font-bold font-sans text-slate-800">{row.carrier}</td>
                  <td className="py-3 px-3 text-center">
                    <span className={`px-2 py-1 rounded font-bold ${row.indiGo >= 0.9 ? "bg-rose-100 text-rose-800" : row.indiGo >= 0.8 ? "bg-amber-100 text-amber-800" : "bg-slate-100 text-slate-700"}`}>
                      {row.indiGo.toFixed(2)}
                    </span>
                  </td>
                  <td className="py-3 px-3 text-center">
                    <span className={`px-2 py-1 rounded font-bold ${row.airIndia >= 0.9 ? "bg-rose-100 text-rose-800" : row.airIndia >= 0.8 ? "bg-amber-100 text-amber-800" : "bg-slate-100 text-slate-700"}`}>
                      {row.airIndia.toFixed(2)}
                    </span>
                  </td>
                  <td className="py-3 px-3 text-center">
                    <span className={`px-2 py-1 rounded font-bold ${row.spiceJet >= 0.9 ? "bg-rose-100 text-rose-800" : row.spiceJet >= 0.8 ? "bg-amber-100 text-amber-800" : "bg-slate-100 text-slate-700"}`}>
                      {row.spiceJet.toFixed(2)}
                    </span>
                  </td>
                  <td className="py-3 px-3 text-center">
                    <span className={`px-2 py-1 rounded font-bold ${row.akasaAir >= 0.9 ? "bg-rose-100 text-rose-800" : row.akasaAir >= 0.8 ? "bg-amber-100 text-amber-800" : "bg-slate-100 text-slate-700"}`}>
                      {row.akasaAir.toFixed(2)}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Recent Synchronized Surge Log */}
      <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-xs">
        <h3 className="text-sm font-bold text-slate-900 mb-1">Live Synchronous Spike Audit Log</h3>
        <p className="text-xs text-slate-500 mb-4">Real-time alerts flagged when two or more carriers raise fares in identical time intervals without external ATF shocks.</p>

        <div className="space-y-3">
          {synchronizedEvents.map((evt, idx) => (
            <div key={idx} className="bg-slate-50 border border-slate-200 rounded-lg p-3.5 flex flex-col md:flex-row md:items-center justify-between gap-3 text-xs">
              <div className="space-y-1">
                <div className="flex items-center gap-2">
                  <span className="font-mono font-bold text-sm text-slate-900">{evt.route}</span>
                  <span className="bg-slate-200 text-slate-700 text-[10px] font-bold px-2 py-0.5 rounded font-mono">{evt.leadTime}</span>
                  <span className={`text-[10px] font-bold px-2 py-0.5 rounded ${evt.severity === "CRITICAL" ? "bg-rose-100 text-rose-800" : "bg-amber-100 text-amber-800"}`}>
                    {evt.severity}
                  </span>
                  <span className="text-slate-400 text-[11px]">{evt.timestamp}</span>
                </div>
                <div className="text-slate-600 font-medium">
                  {evt.reason} (Correlation: <strong className="font-mono text-rose-600">{evt.correlation}</strong>)
                </div>
                <div className="text-[11px] text-slate-500 flex items-center gap-2">
                  <span className="text-blue-700 font-medium">{evt.carrier1}</span> • <span className="text-indigo-700 font-medium">{evt.carrier2}</span>
                </div>
              </div>

              <div className="flex items-center gap-2 self-end md:self-center">
                <button
                  onClick={handleExportDossier}
                  className="bg-white hover:bg-slate-100 text-slate-700 border border-slate-300 px-3 py-1.5 rounded text-xs font-semibold cursor-pointer transition"
                >
                  Flag for CCI Inquiry
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>

    </div>
  );
}
